baseURL = 'https://www.landmänner-breckenheim.de/'
languageCode = 'de-De'
title = 'Landmänner Breckenheim e.V.'
theme = 'ananke'

DefaultContentLanguage = "de"
SectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
show_reading_time = true
rss = true
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Landmänner sind cool."
recent_posts_number = 3

[params.ananke.social.follow]
new_window_icon = false
networks = [
  "facebook"
]

[params.ananke.social.networks.facebook]
profile = "https://www.facebook.com/profile.php?id=100080038848397"

